# Google Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mmb-portfolio
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/mmb-portfolio:BUILD_ID
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: CLOUD_RUN_SERVICE
          value: "true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mmb-portfolio-jwt-secret
              key: latest
        # CORS not needed for unified deployment serving from same origin
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi